name: Sync remote to github
on:
  workflow_dispatch:
  schedule:
  - cron:  "*/5 * * * *"
  
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://bitbucket.org/lindenlab/viewer.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:Kadah/lindenlab-viewer.git"
          destination_branch: "refs/heads/*"
          destination_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
